### ISSUE TITLE
Exception while executing functions 

### ISSUE THREAD

**Issue by racchen** [Azure/azure-python-siteextensions#17]
Dear, 

I got those exception in my log file recently. Those errors seem related to the site extension. Any idea? 

Exception while executing function: Functions.provision. Microsoft.Azure.WebJobs.Script: Traceback (most recent call last):
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.4\tools\Lib\logging\config.py", line 558, in configure
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.4\tools\Lib\logging\config.py", line 731, in configure_handler
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.4\tools\Lib\logging\handlers.py", line 150, in __init__
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.4\tools\Lib\logging\handlers.py", line 57, in __init__
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.4\tools\Lib\logging\__init__.py", line 1014, in __init__
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.4\tools\Lib\logging\__init__.py", line 1043, in _open
PermissionError: [Errno 13] Permission denied: 'D:\\home\\site\\wwwroot\\provision\\epas.log'

Thanks,

**Comment by zooba** [comment]
Something in your code is trying to write to a file in what is apparently a protected location (your webapp shouldn't be self-modifying, which is essentially what writing to `wwwroot` is doing).

I can't see from the traceback which code is trying to configure logging, but you likely need to pass in a different directory somewhere. There is a writable directory at `D:\home\LogFiles` where you can put log files, and then any tools that retrieve log files from an app service instance should be able to collect them automatically for you.
