### ISSUE TITLE
python361x86 and python361x64 pip broken

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-python-siteextensions#7]
```console
> D:\home\SiteExtensions\python361x86\python361x86\python.exe -m pip install flask==0.12
Collecting flask==0.12
  Using cached Flask-0.12-py2.py3-none-any.whl
Collecting click>=2.0 (from flask==0.12)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask==0.12)
  Using cached Werkzeug-0.12.1-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask==0.12)
  Using cached Jinja2-2.9.5-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask==0.12)
  Using cached itsdangerous-0.24.tar.gz
', 'Error': 'Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.6.1\tools\Lib\site-packages\pip\req\req_install.py", line 387, in setup_py
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.6.1\tools\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
ModuleNotFoundError: No module named 'six'
```

Saw by @huguesv , I reproduced from a clean WebApp and fresh install

**Comment by lmazuel** [comment]
It works in:
python2711x64
python2712x64
python2712x86
python351x64
python360x64
