### ISSUE TITLE
python353x68 and python353x64 pip is broken

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-python-siteextensions#8]
Same as https://github.com/Azure/azure-python-siteextensions/issues/7

```console
Collecting flask==0.12
  Using cached Flask-0.12-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask==0.12)
  Using cached itsdangerous-0.24.tar.gz
', 'Error': 'Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.3\tools\Lib\site-packages\pip\req\req_install.py", line 387, in setup_py
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.5.3\tools\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
ImportError: No module named 'six'
```

@huguesv

**Comment by lmazuel** [comment]
Same with python352x86 and python352x64

**Comment by lmazuel** [comment]
Same with python2713x86 and python2713x64

**Comment by lmazuel** [comment]
It works in:
python2711x64
python2712x64
python2712x86
python351x64
python360x64

**Comment by zooba** [comment]
This is because of a setuptools change that now requires `six` to be separately installed. I'll add it to the package builds and update all the ones you've listed.

**Comment by zooba** [comment]
Fixed and new packages have been uploaded
