### ISSUE TITLE
python361x86 : No module named pyparsing

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-python-siteextensions#9]
D:\home\SiteExtensions\python361x86\python361x86\python.exe -m pip install flask==0.12

```console
Collecting flask==0.12
  Using cached Flask-0.12-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask==0.12)
  Using cached Werkzeug-0.12.1-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask==0.12)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting click>=2.0 (from flask==0.12)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask==0.12)
  Using cached itsdangerous-0.24.tar.gz
', 'Error': 'Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.6.1\tools\Lib\site-packages\pip\req\req_install.py", line 387, in setup_py
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.6.1\tools\Lib\site-packages\setuptools\__init__.py", line 12, in <module>
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.6.1\tools\Lib\site-packages\setuptools\version.py", line 1, in <module>
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.6.1\tools\Lib\site-packages\pkg_resources\__init__.py", line 72, in <module>
  File "D:\Repos\azure-python-siteextensions\source_packages\pythonx86.3.6.1\tools\Lib\site-packages\packaging\requirements.py", line 9, in <module>
ModuleNotFoundError: No module named 'pyparsing'
```

**Comment by lmazuel** [comment]
Same with 
python361x64
all python360
all python353
all python352
all python2713
all python2712

**Comment by lmazuel** [comment]
Same python353x86

**Comment by lmazuel** [comment]
Same python352x64

**Comment by lmazuel** [comment]
Same python2713x86

**Comment by lmazuel** [comment]
Same python2713x64

**Comment by lmazuel** [comment]
Same python353x64

**Comment by zooba** [comment]
Should be fixed for good - we don't need to filter out any packages anymore because we start from a clean install. I'll upload new packages now.
